class FormElements:

    gender = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[2]/p[2]/span/span/span[1]/label/span"
    dob = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[3]/p[2]/input"
    full_name = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[4]/p[2]/span/input"
    email = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[5]/p[2]/span/input"
    cnic = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[6]/p[2]/span/input"
    contact_number = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[7]/p[2]/span/input"
    address = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[8]/p[2]/span/input"
    city = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[9]/p[2]/span/input"
    qualification = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[11]/p[2]/span/select"
    comp_year = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[12]/p[2]/span/select"
    university = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[13]/p[2]/span/input"
    cgpa = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[14]/p[2]/span/input"
    work = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[15]/p[2]/span/span/span[2]/label/span"
    exp_salary = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[16]/p[2]/span/input"
    exp_date = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[17]/p[2]/input"
    hear_about_us = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[18]/p[2]/span/input"
    experience = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[19]/p[2]/span/select"
    send_resume = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[20]/p[2]/span/input"
    submit = "/html/body/div[4]/div/div[1]/div/div/div[4]/div/form/div[2]/ul/li[21]/p/input"