class HomePageElements:

    expertise = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[5]/a"
    about_us = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[2]/a"
    life_at_pf = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[4]/a"
    trainee_program = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[7]/a"
    career = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[3]/a"
    apply_now = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[8]/a"
    career_drop1 = "menu-item-35"
    career_drop2 = "menu-item-36"
    resource = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[6]/a"
    resource_drop1 = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[6]/ul/li[1]/a"
    resource_drop2 = "/html/body/div[2]/header/div[2]/div/div[2]/div/nav/div/ul/li[6]/ul/li[2]/a"
    pf_logo = "/html/body/div[2]/header/div[2]/div/div[1]/div[1]/a/picture/img[2]"
    footer_life_at_pf = "/html/body/div[4]/footer/div/div/div[2]/div[1]/ul/li[1]/a"
    footer_our_teammate = "/html/body/div[4]/footer/div/div/div[2]/div[1]/ul/li[2]/a"
    footer_in_house_privacy = "/html/body/div[4]/footer/div/div/div[2]/div[1]/ul/li[3]/a"
    footer_iso_certificates = "/html/body/div[4]/footer/div/div/div[2]/div[1]/ul/li[4]/a"
    footer_career = "/html/body/div[4]/footer/div/div/div[2]/div[2]/ul/li[1]/a"
    footer_job_position = "/html/body/div[4]/footer/div/div/div[2]/div[2]/ul/li[2]/a"
    footer_send_resume = "/html/body/div[4]/footer/div/div/div[2]/div[2]/ul/li[3]/a"
    footer_track_application = "/html/body/div[4]/footer/div/div/div[2]/div[2]/ul/li[4]/a"
    footer_ransomware = "/html/body/div[4]/footer/div/div/div[2]/div[3]/ul/li[1]/a"
    footer_fintech = "/html/body/div[4]/footer/div/div/div[2]/div[3]/ul/li[2]/a"
    footer_life_changing = "/html/body/div[4]/footer/div/div/div[2]/div[3]/ul/li[3]/a"
    footer_ai_career = "/html/body/div[4]/footer/div/div/div[2]/div[3]/ul/li[4]/a"
    pf_footer_logo = "/html/body/div[4]/footer/div/div/div[1]/div/a/img"
    footer_apply_now = "/html/body/div[4]/footer/div/div/div[2]/div[4]/ul/li[3]/a"
    facebook_link = "/html/body/div[4]/footer/div/div/div[2]/div[4]/div/ul/li[1]/a/img"
    linkedin_link = "/html/body/div[4]/footer/div/div/div[2]/div[4]/div/ul/li[3]/a/img"
    insta_link = "/html/body/div[4]/footer/div/div/div[2]/div[4]/div/ul/li[4]/a/img"
    youtube_link = "/html/body/div[4]/footer/div/div/div[2]/div[4]/div/ul/li[5]/a/img"
    privacy_policy_last = "/html/body/div[4]/footer/div/div/div[4]/div/p/a"



